### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by blangero** [eight04/aigis-exp-calculator#1]
Hi Eight04,

This tool is awesome, especially to beginners to this game, like me. It helped a lot.

For me the features are already enough, but I think some improvements can make life easier.

1. after selecting rarity, how about propose some levels to be selected directly, such like while selecting rarity Gold, users then can select lvl 50 and lvl 60 directly.
稀有度: Gold(dropbox) 
目標等級:(input); lvl50(single selection) lvl60(single selection)

2. add buttons '<'(or '-') '>'(or'+') after the 聖靈 number input, so while using mobile devices, we don't even need keyboard.

3. add 'customize' in 聖靈, then users can input any exp, such like 2000 * 1.5 * 1.5 * 1.5, or when there's female exp*3 + male exp*2.

Of course I tried to improve by myself, the code is nice structured but so many frameworks are required, I installed nodejs, npm, rollup, sirv-cli, but still failed to run the command 'sirv docs', maybe some details can be added to Readme?

Thanks and regards,
Blangero

**Comment by eight04** [comment]
> Of course I tried to improve by myself, the code is nice structured but so many frameworks are required, I installed nodejs, npm, rollup, sirv-cli, but still failed to run the command 'sirv docs', maybe some details can be added to Readme?

1. Install Node.js. I believe that `npm` is included in the installer.
2. Clone the repo.
3. In the project root, run `npm install`. This command installs all required dependencies.
4. Run `npm run dev`. This command spawns a dev server and compiles the source code in real time.

**Comment by eight04** [comment]
Buttons are added in #2.

**Comment by blangero** [comment]
Thanks for the update, working perfectly!
